---
title: "R Notebook"
output: html_notebook
---


```{r}
library(readr)
library(dplyr)
library(stringi)
library(writexl)
library(openxlsx)

```

```{r}
df_raw <- read.csv("SYB66_230_202310_GDP and GDP Per Capita.csv", skip=1, encoding="UTF-8")
# View(df_raw)

```


```{r}
colnames(df_raw)
```
```{r}
df <- subset(df_raw, select = -c(`Region.Country.Area`, `Footnotes`, `Source`))
names(df) <- c("region", "year", "series", "value")
head(df)
```
```{r}
unique(df$series)
```

```{r}
df <- subset(df, series == "GDP per capita (US dollars)" & year == "2021")
# unique(df$year)
head(df)
```


```{r}


# read.csv2(file("filename", encoding="UTF-8"))
# df <- stri_enc_toutf8(df)
# df_country <- stri_enc_toutf8(df$region)
# df_country <- apply(df$region, 1, stri_enc_toutf8)
# df_country <- df$region
# new_df <- df[, c("col1", "col3")]
# df_country <- df[, "region"]
# df %>% select(col1, col3)
df_country <- df |> select(region)
# df_country <- stri_enc_toutf8(df_country)
# df_country <- iconv(df_country, to="UTF-8")
df_country
```
```{r}
write.xlsx(df_country, "country_list.xlsx")
```

```{r}
write_xlsx(df_country, "country_list2.xlsx")
df_country
```
